mtbs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cinemas.urls')),
    path('users/', include('users.urls')),
    path('movies/', include('movies.urls')),
    path('sessoes/', include('sessoes.urls')),
    path('tickets/', include('tickets.urls')),
]

tickets/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('tickets/<int:sessionId>', views.tickets, name='tickets'),
    path('ticket/<int:ticketId>', views.sessionTicket, name='sessionTicket'),
    path('activeTickets/',views.activeTickets, name='activeTickets'),
    path('ticketHistory/',views.ticketHistory, name='ticketHistory'),
    path('cancelledTicket/',views.cancelledTicket, name='cancelledTicket'),
    path('cancelTicket/<int:ticket_id>/', views.cancelTicket, name='cancelTicket'),
    path('payTicket/<int:ticket_id>/', views.payTicket, name='payTicket'),
    path('coupons/', views.coupons, name='coupons'),
    path('newcoupon/', views.newCoupon, name='newCoupon'),
    path('editcoupon/<int:coupon_id>/', views.editCoupon, name='editCoupon'),
]

tickets/models.py
from django.db import models
from users.models import Profile
from sessoes.models import Session
from decimal import Decimal
from django.utils import timezone
from django.core.exceptions import ValidationError

class Coupon(models.Model):
    code=models.CharField(max_length=30, unique=True)
    discount=models.DecimalField(max_digits=5, decimal_places=2) 
    active=models.BooleanField(default=True)
    validFrom=models.DateTimeField()
    validUntil=models.DateTimeField()

    def is_valid(self):
        now=timezone.now()
        return self.active and self.validFrom <= now <= self.validUntil

    def __str__(self):
        return f"{self.code} - {self.discount}%"

class Ticket(models.Model):
    TICKET_STATUS=[
        ('DONE', 'Concluído'),
        ('PENDING', 'Pendente'),
        ('CANCELLED', 'Cancelado'),
        ('FREE', 'Livre'),
    ]

    TICKET_TYPES=[
        ('MEIA', 'Meia Entrada'),
        ('IDOSO', 'Idoso'),
        ('NORMAL', 'Normal'),
    ]
    
    session=models.ForeignKey(Session, on_delete=models.CASCADE)
    user=models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    status=models.CharField(max_length=10, choices=TICKET_STATUS, default='FREE')
    seatNumber=models.PositiveIntegerField()
    ticketType=models.CharField(max_length=6, choices=TICKET_TYPES)
    price=models.DecimalField(max_digits=6, decimal_places=2)
    coupon=models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    is_reserved=models.BooleanField(default=False)
    paid=models.BooleanField(default=False)
    purchasedAt=models.DateTimeField(auto_now_add=True)
    history=models.TextField(null=True, blank=True)
    
    def reserve(self, profile, ticketType):
        if not self.is_reserved:
            self.user = profile
            self.is_reserved = True
            self.ticketType = ticketType
            basePrice=self.price

            if self.status=='FREE':
                self.status = 'PENDING'

            #descontos de tipos de entrada
            if ticketType == 'MEIA':
                self.price = round(basePrice * Decimal('0.5'), 2)
            elif ticketType == 'IDOSO':
                self.price = round(basePrice * Decimal('0.6'), 2)

            self.save()

        else:
            raise ValueError("Assento já reservado.")
        
    def cancel(self):
        if self.is_reserved:
            TicketCancelled.objects.create(
                original_ticket_id=self.id,
                session=self.session,
                user=self.user,
                seatNumber=self.seatNumber,
                ticketType=self.ticketType,
                price=self.price,
                purchasedAt=self.purchasedAt,
                cancelledAt=timezone.now()
            )
            
            self.user = None
            self.status = 'FREE'
            self.is_reserved = False
            self.paid = False
            self.save()
        else:
            raise ValueError("O ticket não pode ser cancelado.")
        
    def apply_coupon(self, coupon_code):
        #vai verificando por etapas a validade e a existência do cupom
        if not coupon_code:
            return ValidationError("Código de cupom não existente ou inválido.")

        try:
            coupon=Coupon.objects.get(code=coupon_code, active=True)
        except Coupon.DoesNotExist:
            raise ValueError("Cupom não encontrado.")
        
        if not coupon.is_valid():
            raise ValidationError("O cupom está inválido ou expirado.")
        
        discount_amount=(self.price * coupon.discount) / Decimal('100.0')
        self.price=round(self.price - discount_amount, 2)
        self.coupon=coupon
        self.save()
        
        return self.price

class TicketCancelled(models.Model):
    original_ticket_id=models.PositiveIntegerField()
    session=models.ForeignKey(Session, on_delete=models.CASCADE)
    user=models.ForeignKey(Profile, on_delete=models.CASCADE)
    seatNumber=models.PositiveIntegerField()
    ticketType=models.CharField(max_length=6)
    price=models.DecimalField(max_digits=6, decimal_places=2)
    purchasedAt=models.DateTimeField()
    cancelledAt=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Ticket Cancelado - ID Original: {self.original_ticket_id}"


class Payment(models.Model):

    PAYMENT_METHODS = [
        ('CREDIT_CARD', 'Cartão de Crédito'),
        ('DEBIT_CARD', 'Cartão de Débito'),
        ('PIX', 'PIX'),
        ('BOLETO', 'Boleto Bancário'),
    ]

    PAYMENT_STATUS_CHOICES = [
        ('PENDING', 'Pendente'),
        ('COMPLETED', 'Concluído'),
        ('FAILED', 'Falhado'),
        ('REFUNDED', 'Reembolsado'),
    ]

    ticket=models.ForeignKey(Ticket, on_delete=models.CASCADE, null=True, blank=True)
    amount=models.DecimalField(max_digits=6, decimal_places=2)
    discount=models.DecimalField(max_digits=6, null=True, blank=True, decimal_places=2)
    payMethod=models.CharField(max_length=20, choices=PAYMENT_METHODS)
    status=models.CharField(max_length=10, choices=PAYMENT_STATUS_CHOICES, default='PENDING')
    transactionId=models.CharField(max_length=100, unique=True)
    paidAt=models.DateTimeField(null=True, blank=True)
    createdAt=models.DateTimeField(auto_now_add=True)

    def process_payment(self):
        if self.status == 'PENDING':
            self.status = 'COMPLETED'
            self.paidAt = models.DateTimeField(auto_now=True)
            self.ticket.paid = True
            self.ticket.save()
            self.save()
        else:
            raise ValueError("Pagamento não pode ser processado. Status atual: " + self.status)

    def __str__(self):
        return f"Pagamento {self.status} - {self.ticket.user.user.email} - {self.amount} {self.currency}"

tickets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from abc import ABC, abstractmethod
import qrcode.constants
from decimal import Decimal
from django.utils import timezone
from .models import Ticket, Session, TicketCancelled, Payment, Coupon
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from users.models import Profile, CreditCard, DebitCard
from .forms import TicketForm, CouponForm
from django.db import IntegrityError
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.utils.crypto import get_random_string
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from io import BytesIO
from django.core.files.base import ContentFile
import qrcode
from .observers import Subject, TicketEmailObserver

def index(request):
    return render(request, 'cinemas/index.html')

def tickets(request, sessionId):
    try:
        session=Session.objects.get(id=sessionId)
    except Session.DoesNotExist:
        return HttpResponseNotFound("Sessão não encontrada")
    
    tickets=Ticket.objects.filter(session=session)
    context={'session': session, 'tickets': tickets}
    return render(request, 'tickets/tickets.html', context)

@login_required
def ticketHistory(request):
    try:
        tickets = Ticket.objects.filter(user=request.user.profile).order_by('-purchasedAt')
        ticketsc = TicketCancelled.objects.filter(user=request.user.profile).order_by('-cancelledAt')
    except Ticket.DoesNotExist:
        return HttpResponseNotFound("Ticket não encontrado")
    return render(request, 'tickets/ticketHistory.html', {'tickets': tickets, 'ticketsc':ticketsc})

@login_required
def activeTickets(request):
    try:
        active_tickets = Ticket.objects.filter(user=request.user.profile, status__in=['PENDING', 'DONE'])
    except Ticket.DoesNotExist:
        return HttpResponseNotFound("Ticket não encontrado")
    return render(request, 'tickets/activeTickets.html', {'active_tickets': active_tickets})

@login_required
def cancelledTicket(request):
    try:
        ticket_cancelled = TicketCancelled.objects.filter(user=request.user.profile)
    except Ticket.DoesNotExist:
        return HttpResponseNotFound("Ticket não encontrado")
    
    return render(request, 'tickets/cancelledTicket.html', {'ticket_cancelled': ticket_cancelled})


#########################

#implementação do template method para reserva de ticket

class TicketReservationTemplate(ABC):
    def __init__(self, request, ticket, profile):
        self.request = request
        self.ticket = ticket
        self.profile = profile
        self.form = TicketForm(request.POST or None, instance=self.ticket)

    def process(self):
        #esse método vai definir o fluxo da reserva do ticket
        if self.ticket.is_reserved:
            return self.redirect_with_message('tickets', 'Ticket já reservado', self.ticket.session.id)
        
        if self.request.method=='POST' and self.form.is_valid():
            try:
                self.apply_coupon()
                self.reserve_ticket()
                messages.success(self.request, "Ticket reservado com sucesso!")
                return self.redirect('tickets', self.ticket.session.id)
            except Exception as e:
                self.handle_exception(e)
        
        return render(self.request, 'tickets/sessionTicket.html', {'ticket':self.ticket, 'form':self.form})
    
    @abstractmethod
    def apply_coupon(self):
        pass

    @abstractmethod
    def reserve_ticket(self):
        pass

    def handle_exception(self, exception):
        if isinstance(exception, ValidationError):
            self.form.add_error(None, str(exception))
        elif isinstance(exception, IntegrityError):
            self.form.add_error(None, "Erro ao reservar o ingresso. Verifique os dados e tente novamente.")
        else:
            self.form.add_error(None, f"Erro inesperado: {exception}")
    
    def redirect_with_message(self, view_name, message, *args):
        messages.error(self.request, message)
        return HttpResponseRedirect(reverse(view_name, args=args))
    
    def redirect(self, view_name, *args):
        return HttpResponseRedirect(reverse(view_name, args=args))

class DefaultTicketReservation(TicketReservationTemplate):
    def apply_coupon(self):
        coupon_code = self.request.POST.get('coupon_code')
        if not coupon_code:
            return
        
        try:
            coupon = Coupon.objects.get(code=coupon_code, active=True)
        except Coupon.DoesNotExist:
            raise ValidationError("O cupom não foi encontrado ou está expirado.")
        
        # Verifica se o cupom está inválido ou expirado
        if not coupon.is_valid() or coupon.validUntil < timezone.now():
            raise ValidationError("O cupom está expirado ou inválido.")
        
        # Cálculo do desconto baseado no preço atual do ticket
        discount_amount = (self.ticket.price * coupon.discount) / Decimal('100.0')
        discounted_price = round(self.ticket.price - discount_amount, 2)
        self.ticket.price = discounted_price  # Atualiza o preço do ticket com desconto
        self.ticket.coupon = coupon
        self.ticket.save()

    def reserve_ticket(self):
        ticket_type = self.request.POST.get('ticketType')
        print("Valor do tipo de ticket recebido:", ticket_type)
        
        # Verificar se o tipo de ticket é válido
        valid_ticket_types = [key for key, _ in Ticket.TICKET_TYPES]
        if ticket_type not in valid_ticket_types:
            raise ValidationError("Tipo de ticket inválido. Tente novamente.")
        
        # Configurações básicas do ticket
        self.ticket.user = self.profile
        self.ticket.is_reserved = True
        self.ticket.ticketType = ticket_type
        self.ticket.status = 'PENDING'
        
        # Define o preço do ticket baseado no tipo, com valor padrão
        base_price = self.ticket.price
        discounted_price = base_price  # valor padrão

        if ticket_type == 'MEIA':
            discounted_price = round(base_price * Decimal('0.5'), 2)
        elif ticket_type == 'IDOSO':
            discounted_price = round(base_price * Decimal('0.6'), 2)
        
        self.ticket.price = discounted_price 
        self.ticket.save()


@login_required
def sessionTicket(request, ticketId):
    try:
        ticket=Ticket.objects.get(id=ticketId)
    except Ticket.DoesNotExist:
        return HttpResponseNotFound("Ticket não encontrado")
    
    profile = get_object_or_404(Profile, user=request.user)

    reservation = DefaultTicketReservation(request, ticket, profile)
    return reservation.process()

#######################
# implementação do strategy para meios de pagamento

class PaymentStrategy(ABC):
    @abstractmethod
    def pay(self, request, ticket, profile):
        pass
    
    def create_payment(self, ticket, amount, pay_method):
        payment = Payment.objects.create(
            ticket=ticket,
            amount=amount,
            payMethod=pay_method,
            status='COMPLETED',
            transactionId=get_random_string(20)
        )
        ticket.paid=True
        ticket.status='DONE'
        ticket.save()
        return payment

class WalletPayment(PaymentStrategy):
    def pay(self, request, ticket, profile):
        wallet = profile.wallet
        if wallet.balance >= ticket.price:
            wallet.deduct_balance(ticket.price)
            return self.create_payment(ticket, ticket.price, 'WALLET')
        else:
            raise ValueError("Saldo insuficiente na carteira.")

class CreditCardPayment(PaymentStrategy):
    def pay(self, request, ticket, profile):
        card_id = request.POST.get('card_id')
        card = profile.wallet.credit_cards.filter(id=card_id).first()
        if not card:
            raise ValueError("Cartão de crédito não encontrado ou inválido.")
        
        return self.create_payment(ticket, ticket.price, 'CREDIT_CARD')
    
class DebitCardPayment(PaymentStrategy):
    def pay(self, request, ticket, profile):
        card_id = request.POST.get('card_id')
        card = profile.wallet.debit_cards.filter(id=card_id).first()
        if not card:
            raise ValueError("Cartão de débito não encontrado ou inválido.")
        
        return self.create_payment(ticket, ticket.price, 'DEBIT_CARD')
    
class PixPayment(PaymentStrategy):
    def pay(self, request, ticket, profile):
        return self.create_payment(ticket, ticket.price, 'PIX')

@login_required
def payTicket(request, ticket_id):
    try:
        ticket = Ticket.objects.get(id=ticket_id)
    except Ticket.DoesNotExist:
        return HttpResponseNotFound("Ticket não encontrado")
    
    if ticket.paid:
        messages.error(request,"O pagamento já foi efetuado.")
        return HttpResponseRedirect(reverse('ticketHistory'))
    
    profile = request.user.profile
    payment_method = request.POST.get('payment_method')
    #strategy
    strategy = None
    #observer
    subject = Subject()
    email_observer = TicketEmailObserver()
    subject.register_observer(email_observer)

    if payment_method == 'WALLET':
        strategy = WalletPayment()
    elif payment_method == 'CREDIT_CARD':
        strategy = CreditCardPayment()
    elif payment_method == 'DEBIT_CARD':
        strategy = DebitCardPayment()
    elif payment_method == 'PIX':
        strategy = PixPayment()
    else:
        messages.error(request, "Método de pagamento inválido.")
        context = {
            'ticket': ticket,
            'wallet_balance': profile.wallet.balance,
            'credit_cards': profile.wallet.credit_cards.all(),
            'debit_cards': profile.wallet.debit_cards.all()
        }
        return render(request, 'tickets/payTicket.html', context)

    try:

tickets/templates/tickets/activeTickets.html
{% extends 'cinemas/base.html' %}
{% block content %}

<h1>Meus Tickets Ativos</h1>
    {% if active_tickets %}
    {% for ticket in active_tickets %}
    <div class="ticket">
        <div class="item">
            <div class="item-right">
              <h2 class="num">{{ticket.session.date}}</h2>
              <p class="day">Assento {{ticket.seatNumber}}</p>
              <span class="up-border"></span>
              <span class="down-border"></span>
            </div> 
            
            <div class="item-left">
                {% if ticket.paid %}
                    <p class="event" style="color: rgb(200, 10, 120);">Ticket pago!</p>
                {% elif ticket.status == 'PENDING' %}
                <div style="display: flex; justify-content: space-evenly; margin-bottom: 15px;">
                    <button><a href="{% url 'payTicket' ticket.id %}" style="text-decoration: none; color: aliceblue; font-weight: bold;">PAGAR</a></button>

                    <form action="{% url 'cancelTicket' ticket.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background-color: darkgray;">Cancelar Ticket</button>
                    </form>
                </div>
                {% endif %}
              <h2 class="title">{{ticket.session.movie.title}}</h2>
              
              <div class="sce">
                <div class="icon">
                  <i class="fa fa-table"></i>
                </div>
                <p>R${{ ticket.price }} (TIPO: {{ ticket.ticketType }})<br/> {{ticket.session.hour}}</p>
              </div>
              <div class="fix"></div>
              <div class="loc">
                <div class="icon">
                  <i class="fa fa-map-marker"></i>
                </div>
                <p>Status: {{ ticket.get_status_display }} <br/> {{ticket.session.cinema}}</p>
              </div>
              <div class="fix"></div>
              <button class="ticket-session"><a href="{% url 'tickets' ticket.session.id %}" style="text-decoration: none; color: whitesmoke;">Visualizar sessão</a></button>
            </div> 
          </div>
        </div>
    {% endfor %}
    {% else %}
        <p>Você não possui tickets ativos no momento.</p>
    {% endif %}

{% endblock content %}

tickets/templates/tickets/buyTicket.html
{% extends 'cinemas/base.html' %}

{% block content %}

{% endblock %}

tickets/templates/tickets/cancelledTicket.html
{% extends 'cinemas/base.html' %}
{% block content %}

<h1>Histórico de Tickets Cancelados</h1>
    {% for ticket in ticket_cancelled %}
    <div class="ticket">
        <div class="item">
            <div class="item-right">
              <h2 class="num">{{ticket.session.date}}</h2>
              <p class="day">Assento {{ticket.seatNumber}}</p>
              <span class="up-border"></span>
              <span class="down-border"></span>
            </div> 
            
            <div class="item-left">
                {% if ticket.paid %}
                    <p class="event" style="color: rgb(200, 10, 120);">Ticket pago!</p>
                {% elif ticket.status == 'PENDING' %}
                <div style="display: flex; justify-content: space-evenly; margin-bottom: 15px;">
                    <button><a href="{% url 'payTicket' ticket.id %}" style="text-decoration: none; color: aliceblue; font-weight: bold;">PAGAR</a></button>

                    <form action="{% url 'cancelTicket' ticket.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background-color: darkgray;">Cancelar Ticket</button>
                    </form>
                </div>
                {% endif %}
                <p class="event" style="color: rgb(200, 10, 120); font-size: 14px;">Ticket cancelado em: {{ ticket.cancelledAt }}</p>
              <h2 class="title">{{ticket.session.movie.title}}</h2>
              
              <div class="sce">
                <div class="icon">
                  <i class="fa fa-table"></i>
                </div>
                <p>R${{ ticket.price }} (TIPO: {{ ticket.ticketType }})<br/> {{ticket.session.hour}}</p>
              </div>
              <div class="fix"></div>
              <div class="loc">
                <div class="icon">
                  <i class="fa fa-map-marker"></i>
                </div>
                <p>Status: {{ ticket.get_status_display }} <br/> {{ticket.session.cinema}}</p>
              </div>
              <div class="fix"></div>
              <button class="ticket-session"><a href="{% url 'tickets' ticket.session.id %}" style="text-decoration: none; color: whitesmoke;">Visualizar sessão</a></button>
            </div> 
          </div>
        </div>
    {% empty%}
    <p>Você não possui tickets cancelados.</p>
    {% endfor %}

{% endblock content %}

tickets/templates/tickets/coupons.html
{% extends 'cinemas/base.html' %}

{% block content %}

<h2 style="text-align: center; color:ghostwhite; font-family: 'Lexend', sans-serif;">Coupons</h2>
<a href="{% url 'newCoupon' %}" style="color: aliceblue;">novo cupom</a>

<div class="container">
    <div class="card-container">
        {% for coupon in coupons %}
        <div class="card">
            {{ coupon }}
            {% if coupon.active %}
            <h3 style="color: aliceblue;">ATIVO</h3>
            {% endif %}
            {% if user.is_superuser %}
            <a href="{% url 'editCoupon' coupon.id %}" class="btn">Editar cupom</a>
            {% endif %}
        </div>
        {% empty %}
        <div class="card">
            <p>Não há cupons registrados</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

tickets/templates/tickets/editCoupon.html
{% extends 'cinemas/base.html' %}

{% block content %}

<form action="{% url 'editCoupon' coupon.id %}" method='post' style="color: aliceblue;">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Adicionar</button>
</form>

{% endblock %}

tickets/templates/tickets/newCoupon.html
{% extends 'cinemas/base.html' %}

{% block content %}

<form action="{% url 'newCoupon' %}" method='post' style="color: aliceblue;">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Adicionar</button>
</form>

{% endblock %}

tickets/templates/tickets/ticketConfirmation.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Confirmação de Pagamento e Ticket</title>
</head>
<body>
    <h1>Confirmação de Pagamento</h1>
    <p>Olá, {{ user.first_name }}!</p>
    <p>Seu pagamento foi confirmado. Aqui estão os detalhes do seu ticket:</p>
    <ul>
        <li><strong>Filme:</strong> {{ ticket.session.movie.title }}</li><br>
        <li><strong>Sessão:</strong> {{ ticket.session.date }} - {{ ticket.session.hour }}</li><br>
        <li><strong>Assento:</strong> {{ ticket.seatNumber }}</li><br>
        <li><strong>Preço:</strong> R$ {{ ticket.price }}</li><br>
        <li><strong>Método de Pagamento:</strong> {{ payment.get_payMethod_display }}</li><br>
    </ul>
    <p>O QR code para o seu ingresso está anexado a este e-mail. Utilize-o para entrar na sessão.</p><br><br>
    <p>Obrigado por escolher nossa plataforma!</p>
</body>
</html>

tickets/templates/tickets/ticketHistory.html
{% extends 'cinemas/base.html' %}
{% block content %}

<h1>Todos os Meus Tickets</h1>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    {% if tickets %}
    {% for ticket in tickets %}
    <div class="ticket">
        <div class="item">
            <div class="item-right">
              <h2 class="num">{{ticket.session.date}}</h2>
              <p class="day">Assento {{ticket.seatNumber}}</p>
              <span class="up-border"></span>
              <span class="down-border"></span>
            </div> 
            
            <div class="item-left">
                {% if ticket.paid %}
                    <p class="event" style="color: rgb(200, 10, 120);">Ticket pago!</p>
                {% elif ticket.status == 'PENDING' %}
                <div style="display: flex; justify-content: space-evenly; margin-bottom: 15px;">
                    <button><a href="{% url 'payTicket' ticket.id %}" style="text-decoration: none; color: aliceblue; font-weight: bold;">PAGAR</a></button>

                    <form action="{% url 'cancelTicket' ticket.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background-color: darkgray;">Cancelar Ticket</button>
                    </form>
                </div>
                {% else %}
                    <p class="event" style="color: rgb(200, 10, 120); font-size: 14px;">Ticket cancelado em: {{ ticket.cancelledAt }}</p>
                {% endif %}
              <h2 class="title">{{ticket.session.movie.title}}</h2>
              
              <div class="sce">
                <div class="icon">
                  <i class="fa fa-table"></i>
                </div>
                <p>R${{ ticket.price }} (TIPO: {{ ticket.ticketType }})<br/> {{ticket.session.hour}}</p>
              </div>
              <div class="fix"></div>
              <div class="loc">
                <div class="icon">
                  <i class="fa fa-map-marker"></i>
                </div>
                <p>Status: {{ ticket.get_status_display }} <br/> {{ticket.session.cinema}}</p>
              </div>
              <div class="fix"></div>
              {% if ticket.status != 'CANCELLED' %}
                  <button><a href="{% url 'newReview' ticket.id %}" style="text-decoration: none; color: whitesmoke;">Adicionar review</a></button>
              {% endif %}
              <button class="ticket-session"><a href="{% url 'tickets' ticket.session.id %}" style="text-decoration: none; color: whitesmoke;">Visualizar sessão</a></button>
            </div> 
          </div>
        </div>
        {% endfor %}
    {% else %}
        <p>Você não possui tickets.</p>
    {% endif %}

{% endblock content %}

tickets/templates/tickets/tickets.html
{% extends 'cinemas/base.html' %}

{% block content %}
<div style="display: flex; align-items: center; justify-content: center;">
    <h1 style="color: #ebebeb">Ingressos para {{ session.movie.title }} - {{ session.date }}</h1>
</div>
{% if user.is_superuser or user.is_staff %}
<div class="container">
    <div class="card-container">
        {% for ticket in tickets %}
        <div class="card">
            Assento: {{ ticket.seatNumber }}<br>
            {% if ticket.is_reserved %}
            <h4 style="color: crimson;">Status: INDISPONÍVEL</h4>
            <h4>Tipo de Ingresso: {{ ticket.get_ticketType_display }}</h4>
            {{ticket.status}}
            {% else %}
            <h4 style="color: darkgreen;">
                Status: DISPONÍVEL 
                {{ticket.status}}
            </h4>
            <a href="{% url 'sessionTicket' ticket.id %}">comprar</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="ticket-container">
    <div class="ticket-card-container">
        {% for ticket in tickets %}
        <div class="ticket-card">
            <h2 style="color:#d2d1d1;">{{ticket.seatNumber}}</h2>
            {% if ticket.is_reserved %}
                <h2 style="color: #d2d1d1;">OCUPADO</h2>
                <svg xmlns="http://www.w3.org/2000/svg" style="width: 16px; height: 16px; margin-right: 8px;" viewBox="0 0 16 16" fill="currentColor" class="bi bi-person-circle"></svg>
                    <path d="M13.468 12.37C12.758 11.226 11.421 10.5 8 10.5s-4.758.726-5.468 1.87A6.982 6.982 0 0 0 8 15a6.982 6.982 0 0 0 5.468-2.63zM8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 13a6 6 0 1 1 0-12 6 6 0 0 1 0 12z"/>
                </svg>
            {% else %}
            <a class="buyticket" href="{% url 'sessionTicket' ticket.id %}">Comprar</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>


{% endif %}

{% endblock %}